### ISSUE TITLE
Could you share training records about cifar100, i can't reproduce your results 

### ISSUE THREAD

**Issue by summertaiyuan** [BIT-DA/MetaSAug#5]
I run many times for your work.
For balance ratio = 0.01, the result i run is about 47%,not 48%.
The other results are no different from LDAM actually.

**Comment by kxgong** [comment]
Here is part of my training log. I hope it will be helpful.

Epoch: [182][0/107]     Loss 1.9380 (1.9380)    Prec@1 90.000 (90.000)
Epoch: [182][100/107]   Loss 1.7493 (1.5987)    Prec@1 93.000 (91.317)
Test: [0/100]   Time 0.103 (0.103)      Loss 0.0000 (0.0000)    Prec@1 51.000 (51.000)
 * Prec@1 47.960
Epoch: [183][0/107]     Loss 1.4702 (1.4702)    Prec@1 97.000 (97.000)
Epoch: [183][100/107]   Loss 1.7307 (1.6746)    Prec@1 91.000 (91.297)
Test: [0/100]   Time 0.101 (0.101)      Loss 0.0000 (0.0000)    Prec@1 50.000 (50.000)
 * Prec@1 48.010
Epoch: [184][0/107]     Loss 1.9534 (1.9534)    Prec@1 90.000 (90.000)
Epoch: [184][100/107]   Loss 2.2372 (1.6751)    Prec@1 95.000 (91.188)
Test: [0/100]   Time 0.099 (0.099)      Loss 0.0000 (0.0000)    Prec@1 47.000 (47.000)
 * Prec@1 47.990
Epoch: [185][0/107]     Loss 1.6800 (1.6800)    Prec@1 92.000 (92.000)
Epoch: [185][100/107]   Loss 1.3114 (1.7329)    Prec@1 90.000 (90.772)
Test: [0/100]   Time 0.092 (0.092)      Loss 0.0000 (0.0000)    Prec@1 51.000 (51.000)
 * Prec@1 48.120
Epoch: [186][0/107]     Loss 1.8858 (1.8858)    Prec@1 95.000 (95.000)
Epoch: [186][100/107]   Loss 1.1080 (1.7624)    Prec@1 92.000 (91.376)
Test: [0/100]   Time 0.094 (0.094)      Loss 0.0000 (0.0000)    Prec@1 49.000 (49.000)
 * Prec@1 48.150
Epoch: [187][0/107]     Loss 1.8225 (1.8225)    Prec@1 89.000 (89.000)
Epoch: [187][100/107]   Loss 1.9927 (1.7644)    Prec@1 94.000 (91.119)
Test: [0/100]   Time 0.095 (0.095)      Loss 0.0000 (0.0000)    Prec@1 51.000 (51.000)
 * Prec@1 47.850
Epoch: [188][0/107]     Loss 1.9763 (1.9763)    Prec@1 93.000 (93.000)
Epoch: [188][100/107]   Loss 1.9467 (1.8209)    Prec@1 94.000 (91.010)
Test: [0/100]   Time 0.101 (0.101)      Loss 0.0000 (0.0000)    Prec@1 49.000 (49.000)
 * Prec@1 48.000
Epoch: [189][0/107]     Loss 1.8054 (1.8054)    Prec@1 95.000 (95.000)
Epoch: [189][100/107]   Loss 1.7382 (1.8227)    Prec@1 91.000 (91.525)
Test: [0/100]   Time 0.093 (0.093)      Loss 0.0000 (0.0000)    Prec@1 50.000 (50.000)
 * Prec@1 47.820
Epoch: [190][0/107]     Loss 1.1335 (1.1335)    Prec@1 93.000 (93.000)
Epoch: [190][100/107]   Loss 1.6414 (1.8425)    Prec@1 96.000 (91.663)
Test: [0/100]   Time 0.096 (0.096)      Loss 0.0000 (0.0000)    Prec@1 49.000 (49.000)
 * Prec@1 48.010
Epoch: [191][0/107]     Loss 1.6737 (1.6737)    Prec@1 93.000 (93.000)
Epoch: [191][100/107]   Loss 2.6060 (1.8657)    Prec@1 92.000 (91.089)
Test: [0/100]   Time 0.096 (0.096)      Loss 0.0000 (0.0000)    Prec@1 50.000 (50.000)
 * Prec@1 47.880
Epoch: [192][0/107]     Loss 1.8460 (1.8460)    Prec@1 92.000 (92.000)
Epoch: [192][100/107]   Loss 1.8993 (1.9203)    Prec@1 92.000 (91.178)
Test: [0/100]   Time 0.097 (0.097)      Loss 0.0000 (0.0000)    Prec@1 48.000 (48.000)
 * Prec@1 47.970
Epoch: [193][0/107]     Loss 1.8133 (1.8133)    Prec@1 86.000 (86.000)
Epoch: [193][100/107]   Loss 2.3795 (1.8933)    Prec@1 91.000 (91.970)
Test: [0/100]   Time 0.101 (0.101)      Loss 0.0000 (0.0000)    Prec@1 49.000 (49.000)
 * Prec@1 47.880
Epoch: [194][0/107]     Loss 1.6364 (1.6364)    Prec@1 95.000 (95.000)
Epoch: [194][100/107]   Loss 1.5571 (1.9714)    Prec@1 91.000 (91.416)
Test: [0/100]   Time 0.099 (0.099)      Loss 0.0000 (0.0000)    Prec@1 52.000 (52.000)
 * Prec@1 48.060
Epoch: [195][0/107]     Loss 1.7182 (1.7182)    Prec@1 92.000 (92.000)
Epoch: [195][100/107]   Loss 2.5524 (1.9754)    Prec@1 89.000 (91.178)
Test: [0/100]   Time 0.096 (0.096)      Loss 0.0000 (0.0000)    Prec@1 49.000 (49.000)
 * Prec@1 47.950
Epoch: [196][0/107]     Loss 2.4060 (2.4060)    Prec@1 91.000 (91.000)
Epoch: [196][100/107]   Loss 1.8706 (1.9631)    Prec@1 90.000 (91.347)
Test: [0/100]   Time 0.103 (0.103)      Loss 0.0000 (0.0000)    Prec@1 51.000 (51.000)
 * Prec@1 47.930
Epoch: [197][0/107]     Loss 1.8939 (1.8939)    Prec@1 95.000 (95.000)
Epoch: [197][100/107]   Loss 1.7775 (2.0471)    Prec@1 92.000 (91.347)
Test: [0/100]   Time 0.097 (0.097)      Loss 0.0000 (0.0000)    Prec@1 51.000 (51.000)
 * Prec@1 48.190
Epoch: [198][0/107]     Loss 1.8407 (1.8407)    Prec@1 90.000 (90.000)
Epoch: [198][100/107]   Loss 1.8417 (2.0198)    Prec@1 91.000 (91.505)
Test: [0/100]   Time 0.095 (0.095)      Loss 0.0000 (0.0000)    Prec@1 50.000 (50.000)
 * Prec@1 47.870
Epoch: [199][0/107]     Loss 1.5505 (1.5505)    Prec@1 94.000 (94.000)
Epoch: [199][100/107]   Loss 2.3112 (2.0430)    Prec@1 87.000 (91.248)
Test: [0/100]   Time 0.094 (0.094)      Loss 0.0000 (0.0000)    Prec@1 48.000 (48.000)
 * Prec@1 48.040
